spring.application.name=mascotas

spring.datasource.url=jdbc:postgresql://dpg-d6sg2andiees73cc3gs0-a.oregon-postgres.render.com/mascotas_db_mf0d
spring.datasource.username=mascotas_db_mf0d_user
spring.datasource.password=02pvTmOQzdb1jNPSGafGKgjVtjgYLJlQ
spring.datasource.driver-class-name=org.postgresql.Driver

#mostrar las consultas SQL
spring.jpa.show-sql=true

#configuracion para que actualice el esquema
spring.jpa.hibernate.ddl-auto=update

#optimiza la base de datos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#puerto para Render
server.port=${PORT:8080}
